### ISSUE TITLE
Setup instructions failing

### ISSUE THREAD

**Issue by kelseygonzalez** [favstats/peRspective#4]
hi @favstats ,

In **Setup/Get an API key/step 2**, I'm getting an error with the Perspective API package. 
If I use a google cloud project I have for something else as my active project, I get the error: `There was an error while loading /apis/api/commentanalyzer.googleapis.com/overview?project=bigqueryreddit-272020&folder=&organizationId=. Please try again.`

If I use a newly created google cloud project, the loading circle just infinitely loads (I left it for >10 minutes). 

I have a feeling this is a perspective API problem, but perhaps the setup instructions for the project need more clarification. @AlejandroBeltranA and I both tried and got the same results. Let me know if you're able to provide any insight.

**Comment by favstats** [comment]
Hi @kelseygonzalez!

Thank you for creating an issue! It seems like Perspective has changed the process to get an API key a while ago and I didn't notice because old API keys are still valid.

Apparently, you now need to submit a Google Form and apply for access:
https://developers.perspectiveapi.com/s/docs-get-started

Does that maybe help with your problem? I'll update the description in my README soon.

**Comment by favstats** [comment]
README description updated.
